import = [ "~/.config/alacritty/themes/cyberpunk-neon.toml" ]

[font]
size = 13.5

  [font.offset]
  y = 10

  [font.glyph_offset]
  y = 5

  [font.normal]
  family = "Hack Nerd Font"

[window]
opacity = 0.90
startup_mode = "Fullscreen"
decorations = "buttonless"

  [window.padding]
  x = 5
  y = 5

  [window.dimensions]
  columns = 120
  lines = 40

[cursor]
unfocused_hollow = true

  [cursor.style]
  blinking = "Never"

[env]
TERM = "xterm-256color"

[scrolling]
history = 2_000
