lvim.plugins = {
	"voldikss/vim-floaterm",
	"olexsmir/gopher.nvim",
	"yanskun/gotests.nvim",
	"ray-x/aurora",
	"nyoom-engineering/oxocarbon.nvim",
	"giusgad/pets.nvim",
	"MunifTanjim/nui.nvim",
	"giusgad/hologram.nvim",
	"go-delve/delve",
	"Shougo/vimshell.vim",
	"Shougo/vimproc.vim",
	"sebdah/vim-delve",
	"preservim/vimux",
}
